openapi: 3.0.0

info:
  version: 1.0.0
  title: Device Manager API
  description: Device Manager API

x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
    - Effect: Allow
      Principal: '*'
      Action:
        - execute-api:Invoke
      Resource: '*'

paths:
  /device:
    post:
      security:
        - api_key: []
      tags:
        - device
      summary: create device
      operationId: createDevice
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        $ref: '#/components/requestBodies/device'
      x-amazon-apigateway-integration:
        requestTemplates:
          application/json: |-
             $input.json('$')
        responses:
          default:
            statusCode: '200'
            responseTemplates:
              application/json: |-
                #set($inputRoot = $input.path('$'))

                #if($inputRoot.toString().contains('errorMessage'))
                  #set($context.responseOverride.status = 500)
                  {
                    "message": "The execution of the service failed due to an unexpected condition"
                  }
                #else
                  {
                    "message": "Request accepted"
                  }
                #end

          .*BadRequestError.*:
            statusCode: '400'
            responseTemplates:
              application/json: |-
                {
                  "message": "The execution of the service failed due to invalid request schema"
                }
              
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:646407006236:function:${stageVariables.CreateDevice}/invocations
        httpMethod: POST
        type: aws    
 

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
  schemas:
    device:
      type: object
      properties:
        deviceId:
          type: string
        name:
          type: string
          
  requestBodies:
    device:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/device'
      required: true
    