AWSTemplateFormatVersion : 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Device Configuration Service

Parameters:
  ProjectName:
    Type: String
    Default: device-storage
  NewDeviceTopicArn:
    Type: String
  CloudWatchLogsRetentionInDays:
    Type: String
    Default: 7
  ReservedConcurrentExecutions:
    Type: Number
    Default: 10
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 256
    Tracing: Active
    Tags:
      PROJECT: !Ref ProjectName
      STAGE: !Ref Environment
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  DeviceStorageLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./src/functions/device-storage/index.handler
      Timeout: 60
      ReservedConcurrentExecutions: !Ref ReservedConcurrentExecutions
      Role: !GetAtt DeviceStorageLambdaExecutionRole.Arn
      Environment:
        Variables:
          QUEUE_URL: !Ref DeviceStorageQueue
          DEVICE_STORAGE_TABLE: !Ref DeviceStorageDynamoDBTable
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt DeviceStorageQueue.Arn
            BatchSize: 10
     
  DeviceStorageLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeviceStorageLambda}
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  DeviceStorageLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: !Sub ${ProjectName}-${Environment}-sap-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt DeviceStorageDynamoDBTable.Arn
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt DeviceStorageQueue.Arn

  DeviceStorageQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeviceStorageDlq.Arn
        maxReceiveCount: 5
      MessageRetentionPeriod: 43200 # 12H
      VisibilityTimeout: 60

  DeviceStorageDlq:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 43200 # 12H
      VisibilityTimeout: 60

  DeviceStorageQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: '*'
          Action:
            - sqs:SendMessage
          Resource: !GetAtt DeviceStorageQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref NewDeviceTopicArn
      Queues:
        - !Ref DeviceStorageQueue

  NewDeviceSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt DeviceStorageQueue.Arn
      TopicArn: !Ref NewDeviceTopicArn

  DeviceStorageDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: nameGsi
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL

