AWSTemplateFormatVersion : 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sap Notification Service

Parameters:
  ProjectName:
    Type: String
    Default: sap-notification
  NewDeviceTopicArn:
    Type: String
  CloudWatchLogsRetentionInDays:
    Type: String
    Default: 7
  ReservedConcurrentExecutions:
    Type: Number
    Default: 10
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 256
    Tracing: Active
    Tags:
      PROJECT: !Ref ProjectName
      STAGE: !Ref Environment
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  SapNotificationLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./src/functions/sap-notification/index.handler
      Timeout: 60
      ReservedConcurrentExecutions: !Ref ReservedConcurrentExecutions
      Role: !GetAtt SapNotificationLambdaExecutionRole.Arn
      Environment:
        Variables:
          QUEUE_URL: !Ref SapNotificationQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SapNotificationQueue.Arn
            BatchSize: 10
     
  SapNotificationLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SapNotificationLambda}
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  SapNotificationLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: !Sub ${ProjectName}-${Environment}-sap-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt SapNotificationQueue.Arn

  SapNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SapNotificationDlq.Arn
        maxReceiveCount: 5
      MessageRetentionPeriod: 43200 # 12H
      VisibilityTimeout: 60

  SapNotificationDlq:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 43200 # 12H
      VisibilityTimeout: 60

  SapNotificationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: '*'
          Action:
            - sqs:SendMessage
          Resource: !GetAtt SapNotificationQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref NewDeviceTopicArn
      Queues:
        - !Ref SapNotificationQueue

  NewDeviceSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt SapNotificationQueue.Arn
      TopicArn: !Ref NewDeviceTopicArn

