AWSTemplateFormatVersion : 2010-09-09
Description: Artifacts 

Parameters:
  ProjectName:
    Type: String
    Default: device-manager

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket

  GitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      RepositoryDescription: Device manager system

Outputs:
  RepositoryUrl: 
    Value: !GetAtt GitRepository.CloneUrlHttp
  ArtifactBucket:
    Value: !Ref ArtifactBucket
    
